### ISSUE TITLE
[1.16.5]加入整合包内客户端崩溃

### ISSUE THREAD

**Issue by EnterFor** [LocalizedMC/I18nUpdateMod-NLTS#4]
整合包：ATM6 - To The Sky
Mod版本：I18nUpdateMod-NLTS-Architectury-Forge-1.1.0-1.16.5
前置版本：architectury-1.32.66
使用Java8

[debug.log](https://github.com/BocchiKessokuTeam/I18nUpdateMod-NLTS-Architectury/files/10326963/debug.log)

当我删除此汉化模组后，游戏可以正常进入，我不知道问题出在哪里，没有崩溃报告，不知道日志行不行

**Comment by TexBlock** [comment]
找到了，是本模组的mixin配置文件的`"compatibilityLevel"`设成了`"JAVA_16"`

**Comment by TexBlock** [comment]
一会我修一下

**Comment by TexBlock** [comment]
已在`v1.1.1`修复，此issue关闭
